### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by kunpeng9** [ankipalace/advanced-browser#108]
错误 
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的禁用您已经安装的插件。 
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。 
当你已经发现是因为插件引起的问题，请在我们的支持网站上 [插件支持](https://help.ankiweb.net/discussions/add-ons/) 上报告问题。 
调试信息：
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-12-09 13:09:54

Caught exception:
Traceback (most recent call last):
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 97, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt\browser.py", line 155, in data
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 112, in columnData
    return self.browser.customTypes[type].onData(c, n, type)
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\advanced_fields.py", line 259, in cDateTimeCrt
    return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(c.id/1000))
OSError: [Errno 22] Invalid argument

还有这个错误。

已经禁用了这个插件还是有问题。还是会报错。
https://ankiweb.net/shared/info/874215009
弹出。

错误 
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的禁用您已经安装的插件。 
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。 
当你已经发现是因为插件引起的问题，请在我们的支持网站上 [插件支持](https://help.ankiweb.net/discussions/add-ons/) 上报告问题。 
调试信息：
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-12-07 11:01:25

Caught exception:
Traceback (most recent call last):
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 97, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt\browser.py", line 155, in data
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 112, in columnData
    return self.browser.customTypes[type].onData(c, n, type)
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\advanced_fields.py", line 259, in cDateTimeCrt
    return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(c.id/1000))
OSError: [Errno 22] Invalid argument

Caught exception:
Traceback (most recent call last):
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 97, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt\browser.py", line 155, in data
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 112, in columnData
    return self.browser.customTypes[type].onData(c, n, type)
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\advanced_fields.py", line 259, in cDateTimeCrt
    return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(c.id/1000))
OSError: [Errno 22] Invalid argument

**Comment by hssm** [comment]
This suggests to me that one or more of your cards has an ID that does not resolve to a valid timestamp which the `Created Time (Card)` column requires. I can't know why you have such a card -- perhaps you have an add-on that has modified them.

You may be able to find which cards these are by turning on the `Show internal fields` config and displaying the card ID column like this:
![image](https://user-images.githubusercontent.com/789082/101873634-69923c00-3bdb-11eb-8893-dbaaa80a6466.png)

A normal card ID would look something like this: `1607602708750`.

**Comment by ijgnd** [comment]
there are some databases that have card-ids that don't have the expected length/format. Over the years there have been some threads about this - I think mainly in the old forum at tenderapp and I also had this once in [one of my add-ons](https://github.com/ijgnd/anki__preview_card_edit_note_in_extra_window_linked_from_reviewer/issues/1). 

So it's likely not about the Advanced Browser.

So I'm closing this issue.
