### ISSUE TITLE
Anki 2.1.42 Error Message

### ISSUE THREAD

**Issue by WilliamHJones** [ankipalace/advanced-browser#119]
The error message appears when opening the browser. I tried removing the addon, but the error message still came up, so not sure what was going on there.

An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.42 (8eebfe18) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-16 11:53:33
Add-ons possibly involved: ⁨Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 36, in cmd
  File "aqt/webview.py", line 135, in _onCmd
  File "aqt/webview.py", line 580, in _onBridgeCmd
  File "aqt/toolbar.py", line 169, in _linkHandler
  File "aqt/toolbar.py", line 187, in _browseLinkHandler
  File "aqt/main.py", line 1067, in onBrowse
  File "aqt/__init__.py", line 101, in open
  File "/Users/williamjones/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 208, in __init__
    origInit(self, mw, card, search)
  File "<decorator-gen-154>", line 2, in __init__
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 81, in repl
TypeError: on_browser_init() takes 3 positional arguments but 5 were given

**Comment by ijgnd** [comment]
the solution probably was: check for add-on updates and install them and restart anki - after installing an anki update until recently it could take up to 24 hours until add-on updates were downloaded for the new anki version.
