### ISSUE TITLE
error while searching

### ISSUE THREAD

**Issue by tjardd** [ankipalace/advanced-browser#133]
Hello,
after I go on browse and search for a while I receive the same error twice
I'm not 100% sure if it's solely due to advanced-browser but maybe you guys know how to help me or resolve the issue.
Thanks for your amazing work!

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.32 (dee7d45d) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.13.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-11-15 21:35:39
Add-ons possibly involved: ⁨Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/tjarddunkel/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 174, in paint
    return super(AdvancedStatusDelegate, self).paint(painter, option, index)
  File "aqt/browser.py", line 415, in paint
  File "aqt/theme.py", line 96, in qcolor
  File "aqt/theme.py", line 91, in str_color
Exception: ('no such color:', 'flag7-bg')

Caught exception:
Traceback (most recent call last):
  File "/Users/tjarddunkel/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 174, in paint
    return super(AdvancedStatusDelegate, self).paint(painter, option, index)
  File "aqt/browser.py", line 415, in paint
  File "aqt/theme.py", line 96, in qcolor
  File "aqt/theme.py", line 91, in str_color
Exception: ('no such color:', 'flag7-bg')

Caught exception:
Traceback (most recent call last):
  File "/Users/tjarddunkel/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 174, in paint
    return super(AdvancedStatusDelegate, self).paint(painter, option, index)
  File "aqt/browser.py", line 415, in paint
  File "aqt/theme.py", line 96, in qcolor
  File "aqt/theme.py", line 91, in str_color
Exception: ('no such color:', 'flag7-bg')

Caught exception:
Traceback (most recent call last):
  File "/Users/tjarddunkel/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 174, in paint
    return super(AdvancedStatusDelegate, self).paint(painter, option, index)
  File "aqt/browser.py", line 415, in paint
  File "aqt/theme.py", line 96, in qcolor
  File "aqt/theme.py", line 91, in str_color
Exception: ('no such color:', 'flag7-bg')

**Comment by ijgnd** [comment]
this should be the same error as https://forums.ankiweb.net/t/error-message-while-organizing-my-decks/14987/2

> That’s a known issue when using an outdated and a recent version concurrently, e.g. Anki Desktop 2.1.44 and the newest Ankimobile. You can solve it by updating your desktop client, or removing the new flags (5 to 7) using the the recent client. 

&nbsp;

If you still have the problem: Do the steps from https://faqs.ankiweb.net/when-problems-occur.html

If you still have the problem after disabling all add-ons and restarting anki the problem is not about this add-on.

If the problem disappears without any add-ons but occurs if only the latest version of the advanced browser is installed it's about this add-on. Then please let us know and reopen this issue.
