### ISSUE TITLE
9/26 Update not working with version 2.1.44

### ISSUE THREAD

**Issue by ts3well** [ankipalace/advanced-browser#152]
After updating the Advanced Browser add-on today for Anki, I continue to get this error message upon booting up the app:

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Advanced Browser⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 210, in loadAddons
  File "/Users/Trent/Library/Application Support/Anki2/addons21/874215009/__init__.py", line 6, in <module>
    from . import advancedbrowser
  File "/Users/Trent/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/__init__.py", line 2, in <module>
    from . import basic_fields, config, advanced_fields, note_fields
  File "/Users/Trent/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/advanced_fields.py", line 13, in <module>
    from aqt.operations.card import set_card_flag
ModuleNotFoundError: No module named 'aqt.operations'

**Comment by ijgnd** [comment]
this was an oversight. We already noticed this (see #151). A new version will be uploaded soon.

**Comment by ijgnd** [comment]
it's uploaded. check for add-on updates, then restart anki. if the issue persists of you find other bugs reopen this issue or make a new one.

**Comment by ts3well** [comment]
Thanks, I appreciate it! I have finals next week so thank you for the quick turn-around time.
