### ISSUE TITLE
Addon no longer works on Latest Anki 2.1.55 Beta

### ISSUE THREAD

**Issue by grit780** [ankipalace/advanced-browser#158]
Hello Friends

Installed the latest Anki 2.1.55 beta on Windows ([anki-2.1.55+beta4_e3c3405f-windows-qt5.exe](https://apps.ankiweb.net/downloads/beta/anki-2.1.55%2Bbeta4_e3c3405f-windows-qt5.exe)****

The addon no longer works with an error on startup. Reverting back to beta 3 fixes it. 

Thanks

**Comment by grit780** [comment]
It seems the issue was with the Recolor addon, affecting the advanced Browser. When disabling the addon, the browser now opens. However, there is an issue with the fastbar not appearing correctly

The initial error code was: Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.55 (e3c3405f) Python 3.9.7 Qt 6.4.0 PyQt 6.4.0
Platform: Windows-10-10.0.25231
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-11-22 04:39:55

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 43, in cmd
  File "aqt.webview", line 150, in _onCmd
  File "aqt.webview", line 612, in _onBridgeCmd
  File "aqt.toolbar", line 168, in _linkHandler
  File "aqt.toolbar", line 186, in _browseLinkHandler
  File "aqt.main", line 1158, in onBrowse
  File "aqt", line 130, in open
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 80, in repl
  File "aqt.browser.browser", line 135, in __init__
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 80, in repl
  File "aqt.browser.browser", line 620, in setupSidebar
  File "aqt.browser.sidebar.tree", line 95, in __init__
  File "aqt.browser.sidebar.tree", line 107, in _setup_style
  File "aqt.theme", line 181, in var
TypeError: tuple indices must be integers or slices, not str


Fastbar issue: 

![image](https://user-images.githubusercontent.com/80031609/203208233-0bad00b7-c571-4583-afd1-1ed8a0e04b05.png)
****

**Comment by ijgnd** [comment]
First of all thanks for reporting problems and including the details.

the recolor problem seems to be already tracked with https://github.com/AnKingMed/AnkiRecolor/issues/16 2.1.55 has many changed to the look of anki so problems were expected.

For fastbar there's already a fix in anki from two days ago: https://github.com/ankitects/anki/commit/05b5abb85627f42f5dd8018ef6fb5b0a41984b7b So you need to wait for the next beta or run anki directly from the source code, see [the documentation for coders](https://github.com/ankitects/anki/blob/main/docs/development.md#building-from-source).

Since there are no problems with advanced browser at the moment I'm closing this. If you find more problems please open a new thread.
